/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_juju_app_media_jni_NativeLiveProcess */

#ifndef _Included_com_juju_app_media_jni_NativeLiveProcess
#define _Included_com_juju_app_media_jni_NativeLiveProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_juju_app_media_jni_NativeLiveProcess
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_juju_app_media_jni_NativeLiveProcess_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_juju_app_media_jni_NativeLiveProcess
 * Method:    unInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_juju_app_media_jni_NativeLiveProcess_unInit
  (JNIEnv *, jobject);

/*
 * Class:     com_juju_app_media_jni_NativeLiveProcess
 * Method:    start
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_juju_app_media_jni_NativeLiveProcess_start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_juju_app_media_jni_NativeLiveProcess
 * Method:    stop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_juju_app_media_jni_NativeLiveProcess_stop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_juju_app_media_jni_NativeLiveProcess
 * Method:    inputVideoData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_juju_app_media_jni_NativeLiveProcess_inputVideoData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_juju_app_media_jni_NativeLiveProcess
 * Method:    inputAudioData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_juju_app_media_jni_NativeLiveProcess_inputAudioData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
